# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Download VS Client
      run: |
        curl -O https://cdn.vintagestory.at/gamefiles/stable/vs_client_linux-x64_1.19.8.tar.gz
        tar -zxvf vs_client_linux-x64_1.19.8.tar.gz
        rm -f vs_client_linux-x64_1.19.8.tar.gz
    - name: Build
      run: |
        ls ./
        export VINTAGE_STORY=/home/runner/work/BetterChinese/vintagestory
        echo $VINTAGE_STORY
        dotnet restore
        bash build.sh
  
    - uses: actions/upload-artifact@v4
      with:
        name: BetterChinese
        path: Releases/*.zip
        if-no-files-found: ignore
